transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlib systemFile
vmap systemFile systemFile
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/altera_reset_controller.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_cpu.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_sdram_ctrl.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_tcdm.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_tcim.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_altpll_0.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_jtag_uart.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_avalon_st_adapter_001.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_avalon_st_adapter_006.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_1.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_2.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_performance_counter_0.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_sysid.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_timer_0.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/systemfile.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/altera_avalon_st_clock_crosser.v}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/altera_avalon_st_handshake_clock_crosser.v}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/altera_merlin_burst_adapter_uncmpr.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/altera_merlin_master_agent.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/altera_merlin_master_translator.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/altera_merlin_traffic_limiter.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/altera_merlin_width_adapter.sv}
vlog -vlog01compat -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/altera_std_synchronizer_nocut.v}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_irq_mapper.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_avalon_st_adapter_001_error_adapter_0.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_avalon_st_adapter_006_error_adapter_0.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_cmd_demux_001.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_cmd_mux_001.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_router.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_router_001.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_router_002.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_router_003.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_router_004.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_router_008.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_rsp_demux_001.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work systemFile +incdir+d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/systemfile_mm_interconnect_0_rsp_mux_001.sv}
vcom -93 -work systemFile {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/parport.vhdl}
vcom -93 -work systemFile {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/reader.vhdl}
vcom -93 -work systemFile {d:/syncplicity/z003nc3v/documents/mse/1sem_hs17_18/tsm_embhardw/w3/exercises/lab3parportandtimers/db/ip/systemfile/submodules/writer.vhdl}

vcom -93 -work work {D:/syncplicity/z003nc3v/Documents/MSE/1Sem_HS17_18/TSM_EmbHardw/w3/exercises/lab3ParPortAndTimers/testbench.vhdl}

vsim -t 1ps -L altera -L lpm -L sgate -L altera_mf -L altera_lnsim -L cycloneive -L rtl_work -L work -L systemFile -voptargs="+acc"  testbench

add wave *
view structure
view signals
run -all
